name: flutter_apnabot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Use a modern SDK range

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1                  # For making API calls to Groq
  flutter_markdown: ^0.7.7+1    # For rendering AI responses
  image_picker: ^1.1.2          # For camera and gallery
  file_picker: ^8.0.6           # For picking general files
  shared_preferences: ^2.2.3    # For Storing
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # For generating your app icon

# This new section configures the launcher icon package.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # Path to your logo
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # This section declares your assets so the app can use them.
  assets:
    - assets/images/